name: gdp-demo
homepage: https://github.com/mtonnberg/gdp-demo#readme
license: BSD3
author: Mikael Tönnberg
maintainer: mikael@carboncloud.com
copyright: 2019 Mikael Tönnberg
category: Web
build-type: Simple
extra-source-files: README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - app-settings
  - bytestring
  - bytestring-conversion
  - fast-logger
  - gdp
  - http-types
  - monad-logger
  - mtl
  - network
  - random
  - servant-server
  - servant-options
  - servant
  - servant-foreign
  - servant-gdp
  - text
  - wai
  - wai-cors
  - warp

library:
  source-dirs:
    - src
    - domain-independent
  exposed-modules:
    - Api.ServantApp
  other-modules:
    - Api.ApiDeclaration
    - Api.ApiImplementation
    - Api.Auth
    - Domain.DomainProofs
    - Domain.Animals
    - Effects.Logging.Graylog.GelfMessage
    - Effects.Logging.Graylog.GraylogServer
    - Effects.Logging.Graylog.MonadicLogger
    - Effects.Logging.Graylog.Sending
    - Effects.Logging.LogSettings
    - Effects.Logging.Stdout.Stdout
    - Effects.Logging
    - CoEffects.Settings
    - DomainIndependent.StringConversions
    - DomainIndependent.GDPHumanReadable

executables:
  gdp-demo:
    main: Main.hs
    source-dirs: app
    dependencies: gdp-demo
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
